// <auto-generated />
namespace KurumsalWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updaedataaseforce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updaedataaseforce));
        
        string IMigrationMetadata.Id
        {
            get { return "202108280631344_updae-dataase -force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
